// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    public int Id { get; set; }

    [Column("Category_ID")]
    public int CategoryId { get; set; }

    [StringLength(20)]
    public string Name { get; set; }

    [StringLength(20)]
    public string Descipition { get; set; }

    public int? Price { get; set; }

    [StringLength(30)]
    public string Url { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }
}