// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class User
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("userName")]
    [StringLength(50)]
    public string UserName { get; set; }

    [Required]
    [Column("password")]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("firstName")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("lastName")]
    [StringLength(50)]
    public string LastName { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}